version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: productivetogether
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    expose:
      - "3306"
      
  productivetogether.api:
    depends_on:
      - db
    image: ${DOCKER_REGISTRY-}productivetogetherapi
    build:
      context: .
      dockerfile: ProductiveTogether/Dockerfile
    ports:
      - "8080:443"

volumes:
    db_data: {}